_BASE_: ../Base-AGW.yml

MODEL:
  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True

DATASETS:
  NAMES: ("FastREID_Prototype_1",)
  TESTS: ("FastREID_Prototype_1",)

OUTPUT_DIR: logs/FastREID_Prototype_1/agw_R101-ibn
