_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    WITH_IBN: True

DATASETS:
  NAMES: ("FastREID_Prototype_1",)
  TESTS: ("FastREID_Prototype_1",)

OUTPUT_DIR: logs/FastREID_Prototype_1/bagtricks_R50-ibn
