_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone

DATASETS:
  NAMES: ("FastREID_Prototype_1",)
  TESTS: ("FastREID_Prototype_1",)

OUTPUT_DIR: logs/FastREID_Prototype_1/bagtricks_S50
